# Generated by Django 3.1.2 on 2020-11-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depends_on_brands',
            field=models.BooleanField(default=True),
        ),
    ]
